### ISSUE TITLE
Example server implementing RIPT gRPC proto

### ISSUE THREAD

**Issue by juberti** [WhatIETF/goRIPT#4]

**Comment by ojzuluaga** [comment]
Hi Master, 
I'm trying to run local server/client but even if server is running then client reports TLS issue.
***** SERVER ******
flymac:goRIPT oscarzuluaga$ go run server/main.go 
Using Cert file /etc/letsencrypt/live/ietf107.ript-dev.com/fullchain.pem
Using KeyFile file /etc/letsencrypt/live/ietf107.ript-dev.com/privkey.pem
Host: , H3Port 2399, WSSPort 8080
2020/04/15 20:48:38 riptService: Created Default TrunkGroup [&{trunkAbc /.well-known/ript/v1/providertgs/trunkAbc outbound 1 out: opus;
2 out: opus;
 { }}]
{"time":"2020-04-15T20:48:38.8469-05:00","level":"-","prefix":"-","file":"quic.go","line":"399","message":"Server Url [:2399]"}
{"time":"2020-04-15T20:48:38.847183-05:00","level":"-","prefix":"-","file":"quic.go","line":"427","message":"Starting Server certFile [/etc/letsencrypt/live/ietf107.ript-dev.com/fullchain.pem], keyFile [/etc/letsencrypt/live/ietf107.ript-dev.com/privkey.pem]"}
{"time":"2020-04-15T20:48:38.847206-05:00","level":"INFO","prefix":"-","file":"quic.go","line":"430","message":"New QUIC-H3 Server created.\n"}
Router is ready to serve ...

**** CLIENT *****
flymac:ript_client oscarzuluaga$ ./ript_client --server=https://localhost:2399  --mode=push --xport=h3 --dev
2020/04/15 20:48:57 Server [https://localhost:2399], Mode [push], Transport [h3]
{"time":"2020-04-15T20:48:58.140337-05:00","level":"INFO","prefix":"-","file":"quic_client.go","line":"65","message":"ript_client: registering to the server...[%s]https://localhost:2399/media/join"}
panic: Get "https://localhost:2399/media/join": NO_ERROR: Handshake did not complete in time (Client.Timeout exceeded while awaiting headers)

goroutine 1 [running]:
main.NewQuicClientFace(0xc00013c400, 0xc00013c401, 0xc00004cf40)
	/Users/oscarzuluaga/go/goRIPT/ript_client/quic_client.go:68 +0x4f1
main.main()
	/Users/oscarzuluaga/go/goRIPT/ript_client/main.go:284 +0x719

My question is about certificates, do I need to post on specific folder?? Do they run without problems from TestData Folder??

Thanks for your feedback. I'm trying to understand this idea of RIPT in order to tech somebody else about it.

BR
Oscar
